# Task 3 - Docker Compose

# Write a docker-compose.yml file that will run the following services:
# Write docker-compose.yml file
# version: '3.8'
# must have services front-end and back-end
# must have service for postrgesql database
